# Generated by Django 2.0.7 on 2018-08-17 19:44

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=150, verbose_name='line 1')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('state_parish', models.CharField(max_length=100, verbose_name='state/parish')),
                ('postal_code', models.CharField(blank=True, max_length=12, verbose_name='postal/zip code')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'permissions': (('add_patient_address', 'Can add patient address'), ('change_patient_address', 'Can change patient address'), ('delete_patient_address', 'Can delete patient address')),
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This will be used to identify this branch. E.g. Main', max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('alt_phone', models.CharField(blank=True, max_length=20, verbose_name='alt Phone')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='fax')),
                ('line_1', models.CharField(max_length=150, verbose_name='line 1')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('state', models.CharField(max_length=100, verbose_name='state')),
                ('zip', models.CharField(blank=True, max_length=12, verbose_name='zip Code')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
                'proxy': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='code')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this client should be treated as active. Unselect this instead of deleting client.', verbose_name='active')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(blank=True, help_text='E.g. example@gmail.com', max_length=254, verbose_name='address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': (('add_patient_email', 'Can add patient email'), ('change_patient_email', 'Can change patient email'), ('delete_patient_email', 'Can delete patient email')),
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, help_text='E.g. http://www.example.com', verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': (('add_patient_link', 'Can add patient link'), ('change_patient_link', 'Can change patient link'), ('delete_patient_link', 'Can delete patient link')),
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(choices=[('p', 'Phone'), ('f', 'Fax')], default='p', max_length=1, verbose_name='type')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': (('add_patient_phone', 'Can add patient phone'), ('change_patient_phone', 'Can change patient phone'), ('delete_patient_phone', 'Can delete patient phone')),
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', related_query_name='branch', to='clients.Client'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('name', 'client')},
        ),
    ]
