# Generated by Django 2.0.7 on 2018-08-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='client',
            name='web',
            field=models.URLField(blank=True, help_text='E.g. http://www.example.com', unique=True, verbose_name='website'),
        ),
    ]
