# Generated by Django 2.0.7 on 2018-08-18 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20180817_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='phone',
            new_name='tel_1',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='alt_phone',
            new_name='tel_2',
        ),
    ]
