# Generated by Django 2.0.7 on 2018-08-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20180817_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='tel_1',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='tel_2',
        ),
        migrations.AddField(
            model_name='branch',
            name='prim_tel',
            field=models.CharField(blank=True, max_length=20, verbose_name='prim Tel'),
        ),
        migrations.AddField(
            model_name='branch',
            name='sec_tel',
            field=models.CharField(blank=True, max_length=20, verbose_name='sec Tel'),
        ),
    ]
