# Generated by Django 2.0.7 on 2018-08-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20180818_0927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
