# Generated by Django 2.0.7 on 2018-08-18 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_delete_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Address'),
        ),
    ]
