# Generated by Django 2.0.7 on 2018-08-18 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_branch_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='state_parish',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='postal_code',
            new_name='zip',
        ),
    ]
