# Generated by Django 2.0.7 on 2018-08-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20180818_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='address',
        ),
    ]
