# Generated by Django 2.0.7 on 2018-08-19 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_remove_branch_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='prim_tel',
            new_name='tel_1',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='sec_tel',
            new_name='tel_2',
        ),
    ]
