# Generated by Django 2.0.7 on 2018-08-26 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20180819_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['created_at'], 'verbose_name': 'branch', 'verbose_name_plural': 'branches'},
        ),
    ]
