# Generated by Django 2.0.7 on 2018-08-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=5, verbose_name='middle Initial'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg',
            field=models.CharField(blank=True, help_text='This is number will be included on all prescriptions you download.', max_length=25, null=True, verbose_name='Registration #'),
        ),
    ]
